name: Auto Update
on:
  schedule:
    - cron: "9 9 * * *"
  workflow_dispatch:
env:
  TAG: "latest"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          rm *.js
          gh release download latest --repo jayruin/animated-strokes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Auto Update"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}